### ISSUE TITLE
Long subcommands don't show in subcommand list

### ISSUE THREAD

**Issue by alisolarflare** [TBMCPlugins/ButtonChat#57]
defining a command
"dungeons set entrance one two three four five six seven eight nine"
and running 
/dungeons
does not produce the expected result 
"----Subcommands----
" /dungeons set"
instead it returns
"----Subcommands----"

**Comment by NorbiPeti** [comment]
Hm, the issue is here: https://github.com/TBMCPlugins/ButtonCore/blob/master/src/main/java/buttondevteam/lib/chat/TBMCChatAPI.java#L59
This code bit doesn't support not having a class for /dungeons set so it just skips it.

**Comment by NorbiPeti** [comment]
https://github.com/TBMCPlugins/ButtonCore/commit/ef0b9caa8646286595fc0ab9ba8d9a0aeb064781
