### ISSUE TITLE
Discord chat has the same colour icon as a diamond tier donor.

### ISSUE THREAD

**Issue by NorbiPeti** [TBMCPlugins/ButtonChat#78]
Description: Discord chat when appears in Minecraft has the same colour icon as a diamond tier donor. This can be confusing for the end user, especially at a glace.
Steps to Reproduce:
1. Log in to server with a diamond tier account.
2. Type something in #minecraft-chat in the Chroma Gaming discord.
3. Observe in game chat box.
Result: [D] is a pale blue and diamond tier donor is a pale blue [P]
Expected Result: Two different colours for easy identification.

Reported by @Ghostise

**Comment by Ghostise** [comment]
Fix verified as of June 16th, 2018 on Update 2.
